name: flutter_maintenance
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  animated_digit: ^3.2.1
  connectivity_plus: ^3.0.2
  cupertino_icons: ^1.0.2
  device_info_plus: ^8.0.0
  dio: ^4.0.6
  flutter_screenutil: ^5.6.0
  flutter_svg: ^1.1.6
  get: ^4.6.5
  intl: ^0.18.0
  logger: ^1.1.0
  package_info_plus: ^3.0.2
  shared_preferences: ^2.0.15
  sqflite: ^2.2.2
  url_launcher: ^6.1.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/icons/
